import { StyleSheet } from "react-native";

export const sosModalStyles = StyleSheet.create({
  backdrop: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  backdropNormal: {
    backgroundColor: "rgba(0,0,0,0.65)",
  },
  backdropLocked: {
    backgroundColor: "rgba(127, 29, 29, 0.65)",
  },
  modalCard: {
    width: "100%",
    maxWidth: 400,
    borderRadius: 24,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 10,
  },
  cardNormal: {
    backgroundColor: "#1A2540",
    borderWidth: 2,
    borderColor: "#2A3A55",
  },
  cardActive: {
    backgroundColor: "#FFFFFF",
    borderWidth: 2,
    borderColor: "#EF4444",
  },
  content: {
    padding: 24,
    alignItems: "center",
    textAlign: "center",
  },
  iconCircleRed: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "rgba(239, 68, 68, 0.15)",
    borderWidth: 2,
    borderColor: "rgba(239, 68, 68, 0.25)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  iconCircleGreen: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "rgba(34, 197, 94, 0.12)",
    borderWidth: 2,
    borderColor: "rgba(34, 197, 94, 0.25)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  pulseRadar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "#DC2626",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    shadowColor: "#DC2626",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    elevation: 8,
  },
  title: {
    fontSize: 20,
    fontWeight: "800",
    color: "#FFFFFF",
    marginBottom: 8,
    textAlign: "center",
  },
  titleDark: {
    fontSize: 20,
    fontWeight: "800",
    color: "#071A2E",
    marginBottom: 8,
    textAlign: "center",
  },
  sosActiveTitle: {
    fontSize: 22,
    fontWeight: "900",
    color: "#DC2626",
    letterSpacing: 1,
    marginBottom: 4,
    textAlign: "center",
  },
  description: {
    fontSize: 13,
    lineHeight: 19,
    color: "rgba(255,255,255,0.5)",
    textAlign: "center",
    marginBottom: 24,
  },
  descriptionDark: {
    fontSize: 13,
    lineHeight: 18,
    color: "#6B7280",
    textAlign: "center",
    marginBottom: 16,
  },
  boldWhite: {
    fontWeight: "700",
    color: "#FFFFFF",
  },
  warningRed: {
    fontWeight: "700",
    color: "#F87171",
  },
  timerBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FEF2F2",
    borderWidth: 1,
    borderColor: "#FECACA",
    borderRadius: 12,
    paddingHorizontal: 20,
    paddingVertical: 8,
    marginBottom: 16,
  },
  timerText: {
    fontSize: 26,
    fontWeight: "900",
    fontFamily: "monospace",
    color: "#B91C1C",
  },
  subtextDark: {
    fontSize: 11,
    lineHeight: 16,
    color: "#9CA3AF",
    textAlign: "center",
    maxWidth: 260,
  },
  buttonRow: {
    flexDirection: "row",
    gap: 12,
    width: "100%",
  },
  button: {
    flex: 1,
    minHeight: 46,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
  },
  cancelButton: {
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  cancelText: {
    color: "rgba(255,255,255,0.7)",
    fontWeight: "700",
    fontSize: 14,
  },
  sosButton: {
    backgroundColor: "#EF4444",
  },
  sosButtonText: {
    color: "#FFFFFF",
    fontWeight: "800",
    fontSize: 14,
  },
  understoodButton: {
    width: "100%",
    backgroundColor: "#1A5FB4",
  },
  understoodText: {
    color: "#FFFFFF",
    fontWeight: "800",
    fontSize: 14,
  },
});
