/**
 * dashboard-styles.ts
 *
 * Theme-aware StyleSheet factory for DashboardScreen.
 * Separated from the screen component to keep DashboardScreen focused on
 * behavior and layout composition rather than style definitions.
 *
 * Usage:
 *   const dashStyles = useMemo(() => createDashStyles(colors, isLofi), [colors, isLofi]);
 */

import { StyleSheet } from "react-native";
import type { useAppTheme } from "../../core/theme/ThemeProvider";

export function createDashStyles(colors: ReturnType<typeof useAppTheme>["colors"], isLofi: boolean) {
  return StyleSheet.create({
    offlineBanner: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      backgroundColor: isLofi ? "#FEF3C7" : "rgba(245, 158, 11, 0.08)",
      borderWidth: 1,
      borderColor: isLofi ? colors.warning : "rgba(245, 158, 11, 0.28)",
      borderRadius: 8,
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginBottom: 12,
    },
    offlineBannerText: {
      color: isLofi ? "#92400E" : "#FDE68A",
      fontSize: 12,
      lineHeight: 17,
      flex: 1,
      fontWeight: "600",
    },
    syncBar: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      borderWidth: 1,
      borderColor: isLofi ? colors.warning : "rgba(245, 158, 11, 0.3)",
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
      marginBottom: 12,
    },
    syncBarText: {
      fontSize: 12,
      lineHeight: 16,
      fontWeight: "600",
      flex: 1,
    },
    liveSyncPill: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      alignSelf: "flex-start",
      borderWidth: 1,
      borderRadius: 6,
      paddingHorizontal: 8,
      paddingVertical: 4,
      marginBottom: 10,
    },
    cardWrapper: {
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 10,
      padding: 14,
      marginBottom: 12,
    },
    topRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 12,
      paddingBottom: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    unitTitle: {
      color: colors.text,
      fontWeight: "800",
      fontSize: 17,
      letterSpacing: 0.2,
    },
    routeSubtitle: {
      color: colors.muted,
      fontSize: 12,
      fontWeight: "500",
      marginTop: 2,
    },
    avatarCircle: {
      width: 36,
      height: 36,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
    },
    avatarOnDuty: {
      backgroundColor: colors.primary,
      borderColor: "rgba(255,255,255,0.18)",
    },
    avatarOnBreak: {
      backgroundColor: isLofi ? colors.surface2 : "#0284C7",
      borderColor: isLofi ? colors.border : "#7DD3FC",
    },
    avatarInitial: {
      color: "#FFFFFF",
      fontWeight: "800",
      fontSize: 14,
    },
    breakButton: {
      minHeight: 44,
      width: "100%",
      borderRadius: 8,
      borderWidth: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 10,
    },
    breakButtonOnDuty: {
      borderColor: isLofi ? colors.warning : "rgba(245, 158, 11, 0.35)",
      backgroundColor: isLofi ? colors.surface2 : "rgba(245, 158, 11, 0.1)",
    },
    breakButtonOnBreak: {
      borderColor: isLofi ? colors.success : "rgba(52, 211, 153, 0.35)",
      backgroundColor: isLofi ? colors.surface2 : "rgba(52, 211, 153, 0.1)",
    },
    breakButtonText: {
      fontSize: 13,
      fontWeight: "800",
      letterSpacing: 0.3,
    },
    breakButtonTextOnDuty: {
      color: isLofi ? colors.warning : "#FBBF24",
    },
    breakButtonTextOnBreak: {
      color: isLofi ? colors.success : "#34D399",
    },
    onBreakNotice: {
      color: isLofi ? colors.warning : "rgba(251, 191, 36, 0.8)",
      fontSize: 11,
      textAlign: "center",
      marginTop: 6,
    },
    statusHistoryRow: {
      flexDirection: "row",
      gap: 8,
      marginTop: 12,
    },
    statusBox: {
      flex: 1,
      backgroundColor: colors.surface2,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 8,
      padding: 10,
    },
    statusIndicatorRow: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 8,
    },
    statusDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      marginRight: 6,
    },
    statusHeaderLabel: {
      fontSize: 10,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.8,
      color: colors.muted,
    },
    statusCurrentValue: {
      marginLeft: "auto",
      fontSize: 11,
      fontWeight: "800",
      color: colors.text,
      letterSpacing: 0.2,
    },
    chipsRow: {
      flexDirection: "row",
      gap: 6,
    },
    chip: {
      flex: 1,
      paddingVertical: 7,
      paddingHorizontal: 4,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: "transparent",
      alignItems: "center",
      justifyContent: "center",
    },
    chipAvailable: {
      backgroundColor: "rgba(52, 211, 153, 0.12)",
      borderColor: "rgba(52, 211, 153, 0.4)",
    },
    chipStanding: {
      backgroundColor: "rgba(245, 158, 11, 0.12)",
      borderColor: "rgba(245, 158, 11, 0.4)",
    },
    chipFull: {
      backgroundColor: "rgba(255, 255, 255, 0.06)",
      borderColor: "rgba(255, 255, 255, 0.2)",
    },
    chipText: {
      fontSize: 11,
      fontWeight: "800",
      color: colors.muted,
    },
    historyButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      backgroundColor: colors.surface2,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 8,
      paddingHorizontal: 14,
    },
    historyButtonText: {
      color: colors.text,
      fontSize: 12,
      fontWeight: "700",
    },
    totalCollectedCard: {
      backgroundColor: colors.surface2,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 8,
      padding: 12,
      marginTop: 10,
    },
    totalCollectedTop: {
      flexDirection: "row",
      alignItems: "baseline",
      justifyContent: "space-between",
      marginBottom: 10,
    },
    totalCollectedLabel: {
      fontSize: 10,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.8,
      color: colors.muted,
    },
    totalCollectedAmount: {
      fontSize: 22,
      fontWeight: "900",
      color: colors.text,
      fontVariant: ["tabular-nums"],
    },
    threeCols: {
      flexDirection: "row",
      gap: 6,
    },
    colCard: {
      flex: 1,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 6,
      padding: 8,
    },
    colLabelBlue: {
      fontSize: 9,
      fontWeight: "700",
      textTransform: "uppercase",
      letterSpacing: 0.5,
      color: colors.primaryLight,
    },
    colValueBlue: {
      fontSize: 13,
      fontWeight: "900",
      color: colors.text,
      marginTop: 2,
      fontVariant: ["tabular-nums"],
    },
    colLabelEmerald: {
      fontSize: 9,
      fontWeight: "700",
      textTransform: "uppercase",
      letterSpacing: 0.5,
      color: colors.success,
    },
    colValueEmerald: {
      fontSize: 13,
      fontWeight: "900",
      color: colors.text,
      marginTop: 2,
      fontVariant: ["tabular-nums"],
    },
    colLabelAmber: {
      fontSize: 9,
      fontWeight: "700",
      textTransform: "uppercase",
      letterSpacing: 0.5,
      color: colors.warning,
    },
    colValueAmber: {
      fontSize: 13,
      fontWeight: "900",
      color: colors.text,
      marginTop: 2,
      fontVariant: ["tabular-nums"],
    },
    syncPendingBox: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      backgroundColor: isLofi ? "#FEF3C7" : "rgba(245, 158, 11, 0.08)",
      borderWidth: 1,
      borderColor: isLofi ? colors.warning : "rgba(245, 158, 11, 0.25)",
      borderRadius: 6,
      padding: 10,
      marginTop: 8,
    },
    syncPendingText: {
      fontSize: 11,
      color: isLofi ? "#92400E" : "#FDE68A",
      fontWeight: "600",
    },
    sosTriggerButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      backgroundColor: isLofi ? "#FEE2E2" : "rgba(239, 68, 68, 0.08)",
      borderWidth: 1,
      borderColor: isLofi ? colors.danger : "rgba(239, 68, 68, 0.25)",
      borderRadius: 8,
      paddingVertical: 12,
      marginTop: 18,
    },
    sosTriggerText: {
      color: colors.danger,
      fontWeight: "800",
      fontSize: 13,
      letterSpacing: 0.4,
      textTransform: "uppercase",
    },
  });
}
