import { StyleSheet } from "react-native";
import type { useAppTheme } from "../../core/theme/ThemeProvider";

export function createTripLogbookStyles(
  colors: ReturnType<typeof useAppTheme>["colors"],
  isLofi: boolean,
) {
  return StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.75)",
      justifyContent: "flex-end",
    },
    sheet: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: isLofi ? 4 : 24,
      borderTopRightRadius: isLofi ? 4 : 24,
      maxHeight: "90%",
      borderTopWidth: isLofi ? 2 : 1,
      borderColor: colors.border,
      paddingTop: 16,
      paddingBottom: 28,
      paddingHorizontal: 16,
    },
    headerRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 16,
    },
    title: {
      fontSize: 17,
      fontWeight: "800",
      color: colors.text,
    },
    subtitle: {
      fontSize: 12,
      color: colors.muted,
      marginTop: 2,
    },
    closeButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: isLofi ? colors.surface2 : "rgba(255, 255, 255, 0.08)",
    },
    summaryGrid: {
      flexDirection: "row",
      gap: 8,
      marginBottom: 16,
    },
    summaryCard: {
      flex: 1,
      backgroundColor: isLofi ? colors.surface2 : "rgba(255, 255, 255, 0.04)",
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: isLofi ? 4 : 12,
      padding: 10,
    },
    summaryCardLabel: {
      fontSize: 10,
      fontWeight: "700",
      textTransform: "uppercase",
      color: colors.muted,
    },
    summaryCardValue: {
      fontSize: 15,
      fontWeight: "900",
      color: colors.text,
      marginTop: 3,
    },
    summaryCardSub: {
      fontSize: 10,
      color: colors.muted,
      marginTop: 2,
    },
    activeTripBox: {
      backgroundColor: isLofi ? "#ECFDF5" : "rgba(16, 185, 129, 0.08)",
      borderWidth: 1.5,
      borderColor: isLofi ? colors.success : "rgba(16, 185, 129, 0.35)",
      borderRadius: isLofi ? 4 : 16,
      padding: 14,
      marginBottom: 18,
    },
    activeTripHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 10,
    },
    activeBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      backgroundColor: isLofi ? colors.success : "rgba(16, 185, 129, 0.2)",
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 999,
    },
    activeBadgeText: {
      fontSize: 11,
      fontWeight: "800",
      color: isLofi ? "#FFFFFF" : "#34D399",
      textTransform: "uppercase",
    },
    durationBadge: {
      fontSize: 11,
      color: colors.muted,
      fontWeight: "600",
    },
    routeDirectionRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      marginBottom: 10,
    },
    routeDirectionText: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.text,
    },
    statsRow: {
      flexDirection: "row",
      backgroundColor: isLofi ? colors.surface : "rgba(0, 0, 0, 0.25)",
      borderRadius: isLofi ? 2 : 10,
      padding: 10,
      marginBottom: 12,
    },
    statItem: {
      flex: 1,
      alignItems: "center",
    },
    statItemLabel: {
      fontSize: 9,
      fontWeight: "700",
      textTransform: "uppercase",
      color: colors.muted,
    },
    statItemValue: {
      fontSize: 14,
      fontWeight: "800",
      color: colors.text,
      marginTop: 2,
    },
    buttonRow: {
      flexDirection: "row",
      gap: 8,
    },
    advanceButton: {
      flex: 2,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      backgroundColor: isLofi ? colors.primary : "#1A5FB4",
      paddingVertical: 12,
      borderRadius: isLofi ? 4 : 12,
    },
    advanceButtonText: {
      color: "#FFFFFF",
      fontWeight: "800",
      fontSize: 13,
    },
    switchButton: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 4,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: isLofi ? colors.surface2 : "rgba(255, 255, 255, 0.06)",
      paddingVertical: 12,
      borderRadius: isLofi ? 4 : 12,
    },
    switchButtonText: {
      color: colors.text,
      fontWeight: "700",
      fontSize: 12,
    },
    historySectionTitle: {
      fontSize: 13,
      fontWeight: "700",
      color: colors.muted,
      textTransform: "uppercase",
      letterSpacing: 0.5,
      marginBottom: 10,
    },
    historyCard: {
      backgroundColor: isLofi ? colors.surface2 : "rgba(255, 255, 255, 0.03)",
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: isLofi ? 4 : 12,
      padding: 12,
      marginBottom: 10,
    },
    historyCardTop: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 6,
    },
    historyTripNum: {
      fontSize: 13,
      fontWeight: "800",
      color: colors.text,
    },
    historyDuration: {
      fontSize: 11,
      color: colors.muted,
      fontWeight: "600",
    },
    historyRoute: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.muted,
      marginBottom: 8,
    },
    historyBreakdownRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      borderTopWidth: 1,
      borderColor: isLofi ? colors.border : "rgba(255, 255, 255, 0.06)",
      paddingTop: 8,
    },
    historyPaxBadge: {
      fontSize: 11,
      fontWeight: "700",
      color: isLofi ? colors.primary : "#62A0EA",
    },
    historyRevBadge: {
      fontSize: 12,
      fontWeight: "800",
      color: isLofi ? colors.success : "#34D399",
    },
    emptyBox: {
      paddingVertical: 24,
      alignItems: "center",
      justifyContent: "center",
    },
    emptyText: {
      fontSize: 12,
      color: colors.muted,
      textAlign: "center",
      maxWidth: 240,
      marginTop: 8,
      lineHeight: 18,
    },
    undoRow: {
      flexDirection: "row",
      justifyContent: "center",
      marginTop: 12,
    },
    undoButtonText: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.muted,
      textDecorationLine: "underline",
    },
  });
}
