import { StyleSheet } from "react-native";
import type { useAppTheme } from "../../core/theme/ThemeProvider";

export function createSettingsStyles(
  colors: ReturnType<typeof useAppTheme>["colors"],
  isLofi: boolean
) {
  return StyleSheet.create({
    header: {
      marginBottom: 20,
      marginTop: 6,
    },
    title: {
      fontSize: 24,
      fontWeight: "800",
      color: colors.text,
    },
    subtitle: {
      fontSize: 13,
      color: colors.muted,
      marginTop: 4,
    },
    sectionCard: {
      backgroundColor: colors.surface,
      borderWidth: isLofi ? 1.5 : 1,
      borderColor: colors.border,
      borderRadius: isLofi ? 4 : 20,
      padding: 16,
      marginBottom: 16,
    },
    sectionHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 12,
    },
    sectionHeaderTitle: {
      fontSize: 10,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 1,
      color: colors.muted,
    },
    badgeLock: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    lockIcon: {
      fontSize: 10,
    },
    lockText: {
      fontSize: 10,
      fontWeight: "500",
      color: colors.muted,
    },
    rowsContainer: {
      gap: 8,
    },
    infoRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: isLofi ? colors.surface2 : "rgba(255,255,255,0.03)",
      borderWidth: isLofi ? 1.5 : 1,
      borderColor: colors.border,
      borderRadius: isLofi ? 3 : 14,
      paddingHorizontal: 14,
      paddingVertical: 12,
    },
    rowLabel: {
      fontSize: 12,
      fontWeight: "500",
      color: colors.muted,
    },
    rowValue: {
      fontSize: 13,
      fontWeight: "700",
      color: colors.text,
    },
    emptyShift: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 28,
    },
    emptyIconCircle: {
      width: 52,
      height: 52,
      borderRadius: isLofi ? 4 : 26,
      backgroundColor: isLofi ? colors.surface2 : "rgba(255,255,255,0.03)",
      borderWidth: isLofi ? 1.5 : 1,
      borderColor: colors.border,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 10,
    },
    emptyTitle: {
      fontSize: 13,
      fontWeight: "600",
      color: colors.muted,
    },
    emptySubtitle: {
      fontSize: 11,
      color: colors.muted,
      marginTop: 2,
    },
    prefTitle: {
      fontSize: 13,
      fontWeight: "700",
      color: colors.text,
    },
    prefSubtitle: {
      fontSize: 11,
      color: colors.muted,
      marginTop: 2,
    },
    toggleTrack: {
      width: 48,
      height: 28,
      borderRadius: isLofi ? 4 : 14,
      borderWidth: isLofi ? 1.5 : 0,
      borderColor: isLofi ? colors.border : "transparent",
      padding: 2,
      justifyContent: "center",
    },
    toggleTrackActive: {
      backgroundColor: colors.primary,
    },
    toggleTrackInactive: {
      backgroundColor: isLofi ? colors.surface2 : "#374151",
    },
    toggleThumb: {
      width: 22,
      height: 22,
      borderRadius: isLofi ? 2 : 11,
      backgroundColor: "#FFFFFF",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3,
      elevation: 2,
    },
    toggleThumbActive: {
      alignSelf: "flex-end",
      backgroundColor: "#FFFFFF",
    },
    toggleThumbInactive: {
      alignSelf: "flex-start",
      backgroundColor: isLofi ? colors.muted : "#FFFFFF",
    },
    sosCardButton: {
      flexDirection: "row",
      alignItems: "center",
      gap: 14,
      backgroundColor: isLofi ? "#FEE2E2" : "rgba(239, 68, 68, 0.06)",
      borderWidth: isLofi ? 1.5 : 1,
      borderColor: isLofi ? "#FCA5A5" : "rgba(239, 68, 68, 0.15)",
      borderRadius: isLofi ? 4 : 18,
      padding: 14,
      marginTop: 10,
    },
    sosIconBox: {
      width: 50,
      height: 50,
      borderRadius: isLofi ? 4 : 16,
      backgroundColor: isLofi ? "#FECACA" : "rgba(239, 68, 68, 0.15)",
      borderWidth: isLofi ? 1.5 : 1,
      borderColor: isLofi ? "#F87171" : "rgba(239, 68, 68, 0.2)",
      alignItems: "center",
      justifyContent: "center",
    },
    sosButtonTitle: {
      fontSize: 15,
      fontWeight: "800",
      color: isLofi ? "#B91C1C" : "#F87171",
    },
    sosButtonSubtitle: {
      fontSize: 11,
      color: isLofi ? "#991B1B" : "rgba(248, 113, 113, 0.5)",
      marginTop: 2,
    },
    logoutSection: {
      paddingTop: 16,
      borderTopWidth: 1,
      borderColor: colors.border,
      marginBottom: 24,
    },
    logoutLockBanner: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      marginBottom: 10,
    },
    logoutLockText: {
      fontSize: 12,
      fontWeight: "600",
      color: isLofi ? colors.warning : "rgba(251, 191, 36, 0.8)",
    },
    logoutButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      backgroundColor: isLofi ? colors.surface2 : "rgba(255,255,255,0.04)",
      borderWidth: isLofi ? 1.5 : 1,
      borderColor: colors.border,
      borderRadius: isLofi ? 4 : 14,
      paddingVertical: 13,
    },
    logoutButtonDisabled: {
      opacity: 0.35,
    },
    logoutButtonText: {
      fontSize: 14,
      fontWeight: "700",
      color: isLofi ? colors.text : "rgba(255,255,255,0.6)",
    },
    modalBackdrop: {
      flex: 1,
      backgroundColor: colors.overlay,
      alignItems: "center",
      justifyContent: "center",
      padding: 16,
    },
    modalContent: {
      width: "100%",
      maxWidth: 340,
      backgroundColor: colors.surface,
      borderWidth: isLofi ? 1.5 : 1,
      borderColor: colors.border,
      borderRadius: isLofi ? 4 : 20,
      padding: 24,
      alignItems: "center",
    },
    logoutModalIconCircle: {
      width: 56,
      height: 56,
      borderRadius: isLofi ? 4 : 28,
      backgroundColor: isLofi ? "#FEE2E2" : "rgba(239, 68, 68, 0.15)",
      borderWidth: isLofi ? 1.5 : 0,
      borderColor: isLofi ? "#FCA5A5" : "transparent",
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 14,
    },
    logoutModalTitle: {
      fontSize: 18,
      fontWeight: "800",
      color: colors.text,
      marginBottom: 6,
    },
    logoutModalDescription: {
      fontSize: 12,
      lineHeight: 18,
      color: colors.muted,
      textAlign: "center",
      marginBottom: 20,
    },
    logoutModalButtonsRow: {
      flexDirection: "row",
      gap: 10,
      width: "100%",
    },
    modalButton: {
      flex: 1,
      minHeight: 44,
      borderRadius: isLofi ? 3 : 12,
      alignItems: "center",
      justifyContent: "center",
    },
    cancelModalButton: {
      borderWidth: isLofi ? 1.5 : 1,
      borderColor: colors.border,
      backgroundColor: isLofi ? colors.surface2 : "transparent",
    },
    cancelModalButtonText: {
      color: colors.text,
      fontSize: 13,
      fontWeight: "700",
    },
    confirmLogoutButton: {
      backgroundColor: isLofi ? colors.danger : "#DC2626",
    },
    confirmLogoutButtonText: {
      color: "#FFFFFF",
      fontSize: 13,
      fontWeight: "800",
    },
    clearCacheButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      backgroundColor: isLofi ? colors.surface2 : "rgba(255,255,255,0.04)",
      borderWidth: isLofi ? 1.5 : 1,
      borderColor: colors.border,
      borderRadius: isLofi ? 4 : 14,
      paddingVertical: 13,
      marginTop: 8,
    },
    clearCacheButtonText: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.text,
    },
    clearCacheSubtitle: {
      fontSize: 11,
      lineHeight: 16,
      marginTop: 8,
      textAlign: "center",
      color: colors.muted,
    },
  });
}
